ME-Model-ID: pputida
growth_key: mu
complex_cofactors:
  fes_transfers:
  - G1G01-919-MONOMER
  - G1G01-469-MONOMER
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe_complexes:
    mod_FeFe_cofactor_c: []
    mod_NiFe_cofactor_c: []
trna_misacylation:
  Asn: Asp
lipoprotein_precursors:
  AcrA: PP_1386
  BamB: PP_0856
  BamD: PP_0622
  BamE: PP_4731
  CusC: PP_1384
  LolB: PP_0724
  MetQ: PP_0112
  MltA: PP_4971
  MltB: PP_4805
lipid_modifications:
- pg120_p
- pg140_p
- pg141_p
- pg160_p
- pg161_p
- pg180_p
- pg181_p
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents:
  10fthf_c: -0.000223
  5mthf_c: -0.000223
  accoa_c: -0.000279
  adocbl_c: -0.000223
  amet_c: -0.000223
  bmocogdp_c: -0.000223
  btamp_c: -0.000223
  chor_c: -0.000223
  coa_c: -0.000167
  fad_c: -0.000223
  gthrd_c: -0.000223
  hemeO_c: -0.000223
  malcoa_c: -3.1e-05
  mlthf_c: -0.000223
  mobd_c: -0.002817
  mocogdp_c: -0.000223
  murein3p3p_p: -0.001979
  murein3px4p_p: -0.000326
  murein4p4p_p: -0.007917
  murein4px4p_p: -0.002941
  murein4px4px4p_p: -6.6e-05
  nad_c: -0.001786
  nadh_c: -4.4e-05
  nadp_c: -0.000111
  nadph_c: -0.000335
  pheme_c: -0.000223
  pqqh2_c: -0.000223
  ptrc_c: -0.03327
  pydx5p_c: -0.000223
  pyovd_kt_e: -0.000223
  q8h2_c: -0.000223
  ribflv_c: -0.000223
  sheme_c: -0.000223
  succoa_c: -9.8e-05
  thf_c: -0.000223
  thmnp_c: -0.000223
  thmpp_c: -0.000223
  udcpdp_c: -5.5e-05
flux_of_lipid_constituents:
  clpn140_p: -1.8e-05
  clpn160_p: -0.000578
  clpn161_p: -0.002873
  clpn180_p: -0.000192
  clpn181_p: -0.001309
  cpe160_c: -0.00041
  cpg160_c: -0.000226
  lipopb_c: -0.000223
  lpspput_e: -0.008696
  pe140_c: -0.000251
  pe160_c: -0.007882
  pe161_c: -0.039155
  pe180_c: -0.002622
  pe181_c: -0.017845
  pg140_c: -0.000138
  pg160_c: -0.004354
  pg161_c: -0.021632
  pg180_c: -0.001449
  pg181_c: -0.009859
braun's_lipoprotein: []
braun's_lipid_mod: murein5px4p_p
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- GLNTRAT
- FMETTRS
- ATPM
m-model-path: ./pputidame//building_data/m_model_modified.json
genbank-path: ./pputidame//building_data/genome_modified.gb
biocyc.genes: ./pputidame/inputs/genes.txt
biocyc.prots: ./pputidame/inputs/proteins.txt
biocyc.TUs: ./pputidame/inputs/TUs.txt
biocyc.RNAs: ./pputidame/inputs/RNAs.txt
biocyc.seqs: ./pputidame/inputs/sequences.fasta
df_gene_cplxs_mods_rxns: ./pputidame/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./pputidame//building_data/TUs_from_biocyc.txt
df_matrix_stoichiometry: ./pputidame/building_data/reaction_matrix.txt
df_matrix_subrxn_stoich: ./pputidame/inputs/subreaction_matrix.txt
df_metadata_orphan_rxns: ./pputidame/building_data/orphan_and_spont_reactions.txt
df_metadata_metabolites: ./pputidame/inputs/me_metabolites.txt
out_directory: ./pputidame/
log_directory: ./pputidame/
run_bbh_blast: false
dev_reference: true
include_pseudo_genes: true
selenocysteine_enzymes:
- G1G01-541-MONOMER
- G1G01-542-MONOMER
pg_pe_160:
- G1G01-5487-MONOMER
- G1G01-661-MONOMER
other_lipids:
- G1G01-5127-MONOMER
default_sigma_factor: G1G01-424-MONOMER
rna_polymerases:
  RNAP_G1G013282MONOMER:
    sigma_factor: G1G01-3282-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G01778MONOMER:
    sigma_factor: G1G01-778-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G014920MONOMER:
    sigma_factor: G1G01-4920-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_CPLX1G01176:
    sigma_factor: CPLX1G01-176
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G012226MONOMER:
    sigma_factor: G1G01-2226-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_CPLX1G01182:
    sigma_factor: CPLX1G01-182
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_CPLX1G01177:
    sigma_factor: CPLX1G01-177
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G01386MONOMER:
    sigma_factor: G1G01-386-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G01739MONOMER:
    sigma_factor: G1G01-739-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G011026MONOMER:
    sigma_factor: G1G01-1026-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G014477MONOMER:
    sigma_factor: G1G01-4477-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G01177MONOMER:
    sigma_factor: G1G01-177-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G014916MONOMER:
    sigma_factor: G1G01-4916-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G014517MONOMER:
    sigma_factor: G1G01-4517-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G015452MONOMER:
    sigma_factor: G1G01-5452-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G013189MONOMER:
    sigma_factor: G1G01-3189-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G013068MONOMER:
    sigma_factor: G1G01-3068-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G013814MONOMER:
    sigma_factor: G1G01-3814-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G01940MONOMER:
    sigma_factor: G1G01-940-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G012333MONOMER:
    sigma_factor: G1G01-2333-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G011081MONOMER:
    sigma_factor: G1G01-1081-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G011067MONOMER:
    sigma_factor: G1G01-1067-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G011720MONOMER:
    sigma_factor: G1G01-1720-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G014619MONOMER:
    sigma_factor: G1G01-4619-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G01424MONOMER:
    sigma_factor: G1G01-424-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G014861MONOMER:
    sigma_factor: G1G01-4861-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_G1G011519MONOMER:
    sigma_factor: G1G01-1519-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
ngam: 0.92
gam: 46.7502
translocation_multipliers:
  G1G01-6-MONOMER:
    PP_5412: 2.0
  G1G01-1114-MONOMER:
    PP_4897: 22.0
    PP_0490: 15.5
    PP_0489: 15.5
    PP_0567: 6.25
    PP_2205: 23.0
amino_acid_trna_synthetase:
  ala__L_c: G1G01-4775-MONOMER_mod_zn2(4)
  arg__L_c: G1G01-5433-MONOMER_mod_mg2(1)
  asn__L_c: CPLX_dummy
  asp__L_c: G1G01-1298-MONOMER
  cys__L_c: G1G01-3084-MONOMER_mod_zn2(1)
  gln__L_c: G1G01-3083-MONOMER
  glu__L_c: G1G01-2102-MONOMER_mod_mg2(1)_mod_zn2(1)
  gly_c: CPLX1G01-58
  his__L_c: G1G01-929-MONOMER_mod_mg2(4)
  ile__L_c: G1G01-660-MONOMER_mod_zn2(2)
  leu__L_c: G1G01-5131-MONOMER
  lys__L_c: generic_LYSINEaaRS
  met__L_c: G1G01-1170-MONOMER_mod_zn2(2)
  phe__L_c: CPLX1G01-137_mod_mg2(1)
  pro__L_c: G1G01-1290-MONOMER
  ser__L_c: G1G01-4267-MONOMER_mod_mg2(1)
  thr__L_c: G1G01-2636-MONOMER_mod_zn2(1)
  trp__L_c: G1G01-1398-MONOMER_mod_mg2(1)
  tyr__L_c: G1G01-472-MONOMER
  val__L_c: G1G01-1050-MONOMER_mod_mg2(1)
peptide_release_factors:
  UAG: G1G01-808-MONOMER
  UGA: G1G01-1586-MONOMER
  UAA: generic_RF
braun's_lipoproteins: []
